### ISSUE TITLE
Does not support javacard.security.Signature.ALG_ECDSA_SHA_256?

### ISSUE THREAD

**Issue by stone-ktsujino** [bertrandmartel/javacard-gradle-plugin#8]
I want to crypto test using ALG_ECDSA_SHA_256.
However, TestSuite.setup failed when the flag included.

```18:30:13.891 [DEBUG] [TestEventLogger] Gradle Test Executor 1 STARTED
18:30:13.895 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor] Executing test class test.javacard.TestSuite
18:30:13.896 [DEBUG] [TestEventLogger]
18:30:13.896 [DEBUG] [TestEventLogger] test.javacard.TestSuite STARTED
18:30:14.108 [DEBUG] [TestEventLogger]
18:30:14.108 [DEBUG] [TestEventLogger] test.javacard.TestSuite > classMethod STARTED
18:30:14.109 [INFO] [org.gradle.api.internal.tasks.testing.worker.TestWorker] Gradle Test Executor 1 finished executing tests.
18:30:14.111 [DEBUG] [org.gradle.process.internal.worker.child.ActionExecutionWorker] Completed Gradle Test Executor 1.
18:30:14.124 [DEBUG] [TestEventLogger]
18:30:14.124 [DEBUG] [TestEventLogger] test.javacard.TestSuite > classMethod FAILED
18:30:14.124 [DEBUG] [TestEventLogger]     javacard.framework.SystemException
18:30:14.125 [DEBUG] [TestEventLogger]         at javacard.framework.SystemException.throwIt(Unknown Source)
18:30:14.125 [DEBUG] [TestEventLogger]         at com.licel.jcardsim.base.Simulator.createApplet(Simulator.java:179)
18:30:14.125 [DEBUG] [TestEventLogger]         at com.licel.jcardsim.base.Simulator.installApplet(Simulator.java:219)
18:30:14.125 [DEBUG] [TestEventLogger]         at com.licel.jcardsim.base.Simulator.installApplet(Simulator.java:195)
18:30:14.125 [DEBUG] [TestEventLogger]         at test.javacard.TestSuite.setup(TestSuite.java:105)
18:30:14.125 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:30:14.125 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:30:14.125 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:30:14.126 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
18:30:14.126 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
18:30:14.126 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
18:30:14.126 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
18:30:14.126 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
18:30:14.126 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
18:30:14.126 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
18:30:14.126 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
18:30:14.126 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
18:30:14.126 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
18:30:14.126 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
18:30:14.127 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:30:14.127 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:30:14.127 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:30:14.127 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
18:30:14.127 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
18:30:14.127 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
18:30:14.127 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
18:30:14.127 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
18:30:14.127 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
18:30:14.128 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
18:30:14.128 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:30:14.128 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:30:14.128 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:30:14.128 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
18:30:14.128 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
18:30:14.128 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
18:30:14.128 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
18:30:14.129 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
18:30:14.129 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
18:30:14.129 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
18:30:14.129 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
18:30:14.129 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:748)
18:30:14.129 [DEBUG] [TestEventLogger]
18:30:14.129 [DEBUG] [TestEventLogger] test.javacard.TestSuite FAILED```

Do you know something it?

**Comment by martinpaljak** [comment]
This should be asked from jcardsim folks instead, probably ?

**Comment by stone-ktsujino** [comment]
Thank you martin.
I found this issue :)
https://github.com/licel/jcardsim/issues/125

**Comment by bertrandmartel** [comment]
closing as issue belongs to jcardsim
